const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const { getTranscript } = require('youtube-transcript');
const fetch = require('node-fetch');

const app = express();
app.use(cors());
app.use(bodyParser.json());

const extractVideoID = (url) => {
  const regex = /(?:\?v=|\/embed\/|\.be\/)([^&\n?#]+)/;
  const match = url.match(regex);
  return match ? match[1] : null;
};

app.post('/api/summarize', async (req, res) => {
  const { youtubeUrl } = req.body;
  console.log("🔗 YouTube URL received:", youtubeUrl);

  const videoId = extractVideoID(youtubeUrl);
  console.log("🎥 Extracted Video ID:", videoId);

  if (!videoId) {
    console.log("❌ Invalid YouTube URL");
    return res.json({ error: 'Invalid YouTube URL' });
  }

  try {
    // Get transcript
    const transcriptArray = await getTranscript(videoId);
    console.log("📜 Number of transcript lines:", transcriptArray.length);

    if (!transcriptArray.length) {
      console.log("❌ No transcript found for this video");
      return res.json({ error: 'No transcript available for this video.' });
    }

    const transcriptText = transcriptArray.map(t => t.text).join(' ');
    console.log("📝 Transcript preview (first 300 chars):", transcriptText.slice(0, 300));

    // Call Hugging Face summarization API
    const hfResponse = await fetch('https://api-inference.huggingface.co/models/facebook/bart-large-cnn', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer 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`, // Your token
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ inputs: transcriptText.substring(0, 1024) }) // limit input size
    });

    const data = await hfResponse.json();
    console.log("🤖 Hugging Face API response:", data);

    if (data.error) {
      console.log("❌ Hugging Face API returned an error:", data.error);
      return res.json({ error: 'Hugging Face API error: ' + data.error });
    }

    const summary = data[0]?.summary_text;
    if (!summary) {
      console.log("❌ No summary generated by Hugging Face API");
      return res.json({ error: 'No summary generated.' });
    }

    res.json({ summary });
  } catch (err) {
    console.error("🔥 Error during summarization:", err);
    res.json({ error: 'Failed to summarize video.' });
  }
});

app.listen(5000, () => console.log('Server running on http://localhost:5000'));
